// ==UserScript==
// @name        wt launcher
// @description The Web Tools launcher on any page: drag it anywhere, tap for a short menu. Capture sends the page title, URL and your selection to the Log-Repo shortcut.
// @match       *://*/*
// @require     https://cdn.jsdelivr.net/gh/mehrlander/web-tools@85621a63c5a7b57f249ea7bafd541c7fde0e34f0/userscripts/lib/launcher.js
// @run-at      document-end
// ==/UserScript==
// Generated by scripts/userscript-stub.py; edit the body, then re-run.
window.wtLauncher({ ref: '85621a63c5a7b57f249ea7bafd541c7fde0e34f0' });
