// land.js — where the reader was just sent, and how they get told.
//
// One question, asked after every address the estate resolves: DID THIS LAND
// WHERE I MEANT. A surface that scrolls to a place and says nothing answers it
// only by accident, since a mark that is simply present cannot be told from one
// that was already there, and a reader who followed a link and saw no motion
// cannot tell a hit from a miss.
//
// LIFTED FROM A SECOND IMPLEMENTATION RATHER THAN INVENTED. mehrlander/home's
// budget-drs submittal view has answered this for months, over two very
// different subjects: a block of prose in an office document, and a rectangle
// on a page of a PDF. Its `landOn`, `scrollerOf` and `.landed` live inline in
// projects/budget-drs/submittal/submittal.html, and the Map view's Surfacing
// tab arrived at a near-identical scroller walk independently on 2026-09-04,
// which is the second implementation that makes this a kit. The numbers below
// are that page's, measured there; the smooth scroll and the reduced-motion
// gate are new to this copy. home is the second consumer, not the source of
// truth: when it adopts this, its inline copy goes.
//
//   Land.mark(el, opts?)   scroll to `el`, tint it, fade the tint
//   Land.clear(root)       drop every mark under `root`
//   Land.scrollerOf(el)    the nearest ancestor that actually scrolls
//
// NOT A HIGHLIGHTER, and the distinction decides the timing. A highlighter is
// persistent and means "this matters"; a landing is transient and means "here",
// which is a thing worth saying once. So it fades, and after that the reader is
// looking at the document rather than at the app's answer about the document.
//
// The PDF case is the same colour and the same dwell over a different element:
// an absolutely-positioned rectangle sized from the text layer rather than a
// node in the flow. That is the caller's to build; what it takes from here is
// the tint, so a reader who learns the yellow on one surface reads it on both.
//
// Attaches to window.Land. No CSS of its own: the tint and the fade are
// Tailwind utilities, generated by the browser build the same way a class in a
// component template is, so the page's theme owns the colour.

(() => {
  // WHERE A LANDING SITS, and it is one number for every surface. Centred is
  // wrong twice, and both were measured in home rather than argued: for a SET,
  // the first of seven lit rows in the middle of the pane pushes its siblings
  // off the bottom; for a DOCUMENT, half a screen of the previous section sits
  // above the heading you asked for, which reads as having landed early.
  //
  // A little over a quarter down leaves what was found near the top with its
  // context still visible, which is where a reader expects to have arrived.
  const LAND_AT = 0.28;

  // Long enough to find with the eye after the scroll settles, short enough
  // that it is gone before it becomes furniture.
  const DWELL = 4000;

  // The tint, as utilities rather than a stylesheet. `bg-warning/30` compiles to
  // color-mix(in oklab, var(--color-warning) 30%, transparent), which is
  // character for character what home's `.landed` declares, so the two surfaces
  // are the same yellow by construction rather than by a matched hex.
  const MARK = ['bg-warning/30'];
  // Left on the element after the tint comes off, because the removal is what
  // the transition is FOR: taking these off at the same time would cut the fade
  // and the mark would vanish rather than recede. A colour transition left on a
  // node costs nothing until something changes its colour again.
  const FADE = ['transition-colors', 'duration-1000', 'ease-out'];

  const timers = new WeakMap();

  const reduced = () => {
    try { return matchMedia('(prefers-reduced-motion: reduce)').matches; }
    catch { return false; }
  };

  // The nearest ancestor that actually scrolls vertically. Walked rather than
  // named because one landing serves panes the caller does not enumerate: a
  // list column, a document reader's own column, a deck slide. The `+ 4` is
  // slop against sub-pixel layout reporting a scrollable box that is not.
  function scrollerOf(el) {
    for (let p = el?.parentElement; p; p = p.parentElement) {
      const oy = getComputedStyle(p).overflowY;
      if ((oy === 'auto' || oy === 'scroll') && p.scrollHeight > p.clientHeight + 4) return p;
    }
    return null;
  }

  // Every mark under `root`, off. The caller owns WHEN: a search that lights a
  // set clears before it searches, so a miss leaves nothing lit, while an
  // address naming one row by id has nothing to clear.
  function clear(root) {
    for (const el of (root || document).querySelectorAll('.bg-warning\\/30')) {
      clearTimeout(timers.get(el));
      el.classList.remove(...MARK);
    }
  }

  // Land on `el`. Options:
  //   scroll    false to light it without moving, for every member of a set
  //             after the first: a count that lands on seven rows should move
  //             the reader once and light all seven, not walk down the list.
  //   ifNeeded  scroll only when `el` is not already fully in view, so a tap on
  //             something the reader can see does not jump under the finger.
  //   dwell     ms before the tint starts to go.
  //   smooth    false to jump; ignored (and forced off) under reduced motion.
  //   tint      false to move without marking, for the element the reader is
  //             ALREADY on: a list row whose detail just opened has to be kept
  //             in view when the layout reflows under it, and lighting it would
  //             answer a question nobody asked. The pair is one landing with
  //             two ends, and only the far end is news.
  //
  // ONLY THE SCROLLER MOVES. scrollIntoView walks every scrollable ancestor,
  // and a surface that keeps a list beside a document is a surface where that
  // is wrong: centring a paragraph in the reader scrolled the list it was
  // opened from off the screen. The fallback for an element in no scroller is
  // scrollIntoView, since there the page IS the scroller.
  function mark(el, o = {}) {
    if (!el) return false;
    const smooth = o.smooth !== false && !reduced();
    const behavior = smooth ? 'smooth' : 'auto';
    if (o.scroll !== false) {
      const box = scrollerOf(el);
      const r = el.getBoundingClientRect();
      if (!box) {
        el.scrollIntoView({ block: 'start', behavior });
      } else {
        const b = box.getBoundingClientRect();
        const seen = r.top >= b.top && r.bottom <= b.bottom;
        if (!(o.ifNeeded && seen))
          box.scrollTo({ top: box.scrollTop + (r.top - b.top) - b.height * LAND_AT, behavior });
      }
    }
    if (o.tint === false) return true;
    // Per element rather than one token for the surface, which is the same
    // guarantee home's dwell token buys and a narrower one: a second landing
    // elsewhere cannot clear this one's tint, and a second landing on THIS
    // element restarts its own dwell instead of racing an older timer.
    clearTimeout(timers.get(el));
    el.classList.add(...FADE, ...MARK);
    timers.set(el, setTimeout(() => el.classList.remove(...MARK), o.dwell ?? DWELL));
    return true;
  }

  window.Land = { mark, clear, scrollerOf, LAND_AT, DWELL, MARK, FADE };
})();
