// alpineComponents/repo-menu.js — the actions for one repo, rendered the same
// way wherever they are summoned from.
//
// It reads window.__shell.menuRepo, so the two mounts in show-repo (an anchored
// dropdown under the sidebar crumb, a bottom sheet from a Repos row) show one
// menu in two presentations rather than two menus that have to be kept in step.
//
// A CHEVRON MEANS EXPAND, and nothing else. Rows that navigate carry no
// chevron; rows that leave the app carry an out-arrow. That is the whole reason
// Files and Branches load anything: they were the two rows whose chevron
// promised a submenu and then jumped somewhere instead. Expanding them is also
// the only part of this menu a list row could not offer on its own, since both
// answer "what is inside that repo" for a repo you are not currently in.
//
// Both lists load on first expand, once per repo, through a GH instance for the
// menu's repo (the open repo's own when they coincide). Folders are read with
// no ref, so GitHub answers from the default branch and a repo whose default is
// not `main` still lists.

document.addEventListener('alpine:init', function () {
  Alpine.data('repoMenu', function (opts) {
    const cfg = opts || {};
    return {
      description: 'Action menu for one repo (window.__shell.menuRepo): flat actions plus Files and Branches that expand in place',

      // 'sheet' pads for a thumb; 'menu' is the tighter anchored dropdown.
      size: cfg.size === 'menu' ? 'menu' : 'sheet',
      open: '',            // which row is expanded
      loading: '',         // which row is fetching
      error: '',
      dirs: [],
      branches: [],
      loadedFor: '',       // the repo the two lists above belong to

      template: `
        <div class="flex flex-col py-1">
          <template x-for="item in items" :key="item.key">
            <div>
              <button @click="tap(item)"
                      class="w-full flex items-center gap-3 rounded-lg text-left transition-colors hover:bg-base-200 active:bg-base-300"
                      :class="size === 'sheet' ? 'min-h-14 px-4 text-lg' : 'min-h-11 px-3 text-base'">
                <i class="ph shrink-0 text-base-content/50"
                   :class="[item.icon, size === 'sheet' ? 'text-2xl' : 'text-xl']"></i>
                <span class="min-w-0 flex-1 truncate" x-text="item.label"></span>
                <span x-show="loading === item.key" class="loading loading-spinner loading-xs opacity-40"></span>
                <!-- Two glyphs rather than one rotated: a utility that only
                     ever arrives by toggling a class never gets generated by
                     Tailwind's browser build, so rotate-180 silently did
                     nothing here. Both carets are in the markup from the start. -->
                <i x-show="item.expand && loading !== item.key && open !== item.key"
                   class="ph ph-caret-down shrink-0 text-base-content/30"></i>
                <i x-show="item.expand && loading !== item.key && open === item.key"
                   class="ph ph-caret-up shrink-0 text-base-content/50"></i>
                <i x-show="item.external"
                   class="ph ph-arrow-square-out shrink-0 text-base-content/30"></i>
              </button>

              <!-- The expansion. Indented under its row and scroll-capped, so a
                   repo with eighty branches cannot push the rest of the menu
                   out of reach. -->
              <div x-show="open === item.key" x-cloak
                   class="max-h-56 overflow-y-auto border-l border-base-300 ml-6 pl-1 my-1">
                <template x-for="sub in subFor(item.key)" :key="sub.key">
                  <button @click="pick(item.key, sub)"
                          class="w-full flex items-center gap-2 rounded-lg text-left font-mono transition-colors hover:bg-base-200 active:bg-base-300"
                          :class="[size === 'sheet' ? 'min-h-11 px-3 text-base' : 'min-h-10 px-2 text-sm',
                                   sub.current && 'text-primary font-semibold']">
                    <i class="ph shrink-0 text-base-content/40" :class="sub.icon"></i>
                    <span class="min-w-0 truncate" x-text="sub.label"></span>
                  </button>
                </template>
                <p x-show="!loading && !subFor(item.key).length"
                   class="px-3 py-2 text-sm text-base-content/50" x-text="error || 'Nothing here.'"></p>
              </div>
            </div>
          </template>
        </div>`,

      get repo() { return window.__shell?.menuRepo || ''; },
      get items() { return window.__shell?.repoMenuItems || []; },

      subFor(key) {
        if (key === 'files') return this.dirs;
        if (key === 'branches') return this.branches;
        return [];
      },

      // A GH for the menu's repo: the open repo's own instance when they are the
      // same, else a fresh one carrying the viewer's token.
      _gh() {
        const s = Alpine.store('browser');
        if (this.repo === s.repo && s.gh) return s.gh;
        return new window.GH({ token: window.TOKEN, repo: this.repo });
      },

      tap(item) {
        if (!item.expand) return this.run(item.key);
        if (this.open === item.key) { this.open = ''; return; }
        this.open = item.key;
        this.load(item.key);
      },

      async load(key) {
        if (this.loadedFor === this.repo && this.subFor(key).length) return;
        if (this.loadedFor !== this.repo) { this.dirs = []; this.branches = []; this.loadedFor = this.repo; }
        this.loading = key; this.error = '';
        try {
          const gh = this._gh();
          if (key === 'files') {
            // No ?ref: GitHub answers from the repo's default branch, so a repo
            // whose default is not `main` still lists.
            const rows = await gh.req('contents/');
            this.dirs = (Array.isArray(rows) ? rows : [])
              .filter(r => r.type === 'dir' && !r.name.startsWith('.'))
              .map(r => ({ key: r.path, label: r.name, icon: 'ph-folder', path: r.path }));
          } else {
            const s = Alpine.store('browser');
            const cur = this.repo === s.repo ? (s.ref || s.defaultRef) : '';
            const list = await gh.branches(60);
            this.branches = (Array.isArray(list) ? list : []).map(b => ({
              key: b.name, label: b.name, icon: 'ph-git-branch',
              ref: b.name, current: b.name === cur,
            })).sort((a, b) => (b.current - a.current) || a.label.localeCompare(b.label));
          }
        } catch (e) {
          this.error = e?.status === 404 ? 'Not found, or no access.' : (e?.message || String(e));
        }
        this.loading = '';
      },

      run(key) {
        window.__shell?.runRepoMenu(key);
        this.done();
      },
      pick(key, sub) {
        if (key === 'files') window.__shell?.openRepoAt(this.repo, { path: sub.path });
        else window.__shell?.openRepoAt(this.repo, { ref: sub.ref });
        this.done();
      },
      // Let the host (sheet or dropdown) close itself, and forget the expansion
      // so the menu never reopens half-unfolded.
      done() {
        this.open = '';
        this.$dispatch('repo-menu-done');
      },

      init() {
        this.$el.innerHTML = this.template;
        this.$nextTick(() => Alpine.initTree(this.$el));
      },
    };
  });
});
