#!/usr/bin/env python3
"""Emit a userscript stub and its bookmarklet twin, both pinned at HEAD.

A userscript installed on the phone is a file nobody can edit there, so every
script here is a STUB: a header naming what it matches and one @require pulling
the body from jsDelivr at a commit. Editing a script is then a commit plus a new
pin, and the pin is what this script owns, because doing it by hand means the
same SHA typed into two files and a runbook, which is three chances to ship a
stub pointing at a body that no longer exists.

The pin is a full commit SHA, never a branch: jsDelivr caches a branch address
for about twelve hours, so a stub pinned to `main` is a script whose behaviour
changes at a time nobody chose.

    python3 scripts/userscript-stub.py launcher --match '*://*/*' \\
        --name 'wt launcher' --description '...'

Writes userscripts/<lib>.user.js and bookmarklets/<lib>.js. The body must define
window.wt<Lib> and do nothing on load: the stub calls it, so one file serves the
userscript (extension context, exempt from the page's script-src) and the
bookmarklet (a script tag the page's policy may refuse).
"""
import argparse
import pathlib
import subprocess
import sys

CDN = 'https://cdn.jsdelivr.net/gh/mehrlander/web-tools@{sha}/userscripts/lib/{lib}.js'
ROOT = pathlib.Path(__file__).resolve().parent.parent


def head_sha() -> str:
    return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=ROOT,
                          capture_output=True, text=True, check=True).stdout.strip()


def fn_name(lib: str) -> str:
    return 'wt' + ''.join(p.capitalize() for p in lib.replace('_', '-').split('-'))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('lib', help='basename under userscripts/lib/, without .js')
    ap.add_argument('--name', required=True, help='@name, shown in the install sheet')
    ap.add_argument('--description', required=True, help='@description')
    ap.add_argument('--match', action='append', required=True,
                    help='@match pattern; repeatable')
    ap.add_argument('--run-at', default='document-end')
    ap.add_argument('--sha', help='pin this commit instead of HEAD')
    a = ap.parse_args()

    body = ROOT / 'userscripts' / 'lib' / f'{a.lib}.js'
    if not body.exists():
        print(f'no such body: {body.relative_to(ROOT)}', file=sys.stderr)
        return 1

    fn = fn_name(a.lib)
    if f'window.{fn}' not in body.read_text():
        print(f'{body.relative_to(ROOT)} does not define window.{fn}', file=sys.stderr)
        return 1

    sha = a.sha or head_sha()
    url = CDN.format(sha=sha, lib=a.lib)
    matches = '\n'.join(f'// @match       {m}' for m in a.match)

    (ROOT / 'userscripts' / f'{a.lib}.user.js').write_text(f"""\
// ==UserScript==
// @name        {a.name}
// @description {a.description}
{matches}
// @require     {url}
// @run-at      {a.run_at}
// ==/UserScript==
// Generated by scripts/userscript-stub.py; edit the body, then re-run.
window.{fn}({{ ref: '{sha}' }});
""")

    (ROOT / 'bookmarklets' / f'{a.lib}.js').write_text(
        f"javascript:(s=>{{s.src='{url}';"
        f"s.onload=()=>{fn}({{ref:'{sha}'}});"
        f"document.body.appendChild(s)}})(document.createElement('script'))\n")

    print(f'pinned {a.lib} at {sha[:7]}')
    print(f'  userscripts/{a.lib}.user.js')
    print(f'  bookmarklets/{a.lib}.js')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
